.TH "mainwindow.cpp" 3 "Wed Dec 12 2018" "Version 1.0.0" "Consumidor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QTextBrowser>\fP
.br
\fC#include <QListWidgetItem>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'plotter\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Consumidor from the source code\&.
