.TH "Plotter" 3 "Wed Dec 12 2018" "Version 1.0.0" "Consumidor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plotter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plotter\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlotter\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "void \fBplotGrafico\fP (vector< qint64 > &t, vector< int > &v)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Plotter::Plotter (QWidget * parent = \fCnullptr\fP)"

.SH "Member Function Documentation"
.PP 
.SS "void Plotter::paintEvent (QPaintEvent * event)"

.SS "void Plotter::plotGrafico (vector< qint64 > & t, vector< int > & v)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Consumidor from the source code\&.
