.TH "plotter.h" 3 "Wed Dec 12 2018" "Version 1.0.0" "Consumidor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plotter.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlotter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Consumidor from the source code\&.
