.TH "plotter.cpp" 3 "Wed Dec 12 2018" "Version 1.0.0" "Consumidor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plotter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'plotter\&.h'\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QPen>\fP
.br
\fC#include <QBrush>\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.1415"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PI   3\&.1415"

.SH "Author"
.PP 
Generated automatically by Doxygen for Consumidor from the source code\&.
